[theme]
base="dark"
primaryColor="#10a37f"
backgroundColor="#0e0f12"
secondaryBackgroundColor="#13151a"
textColor="#e7e9ee"
font="sans serif"

[client]
toolbarMode = "auto"
showErrorDetails = false

[server]
# Enhanced for mobile performance
enableWebsocketCompression = true
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Mobile-friendly settings
gatherUsageStats = false
